- type: entity
  id: BaseModularFoundation
  abstract: true
  parent: BaseStructure
  name: ModularFoundation
  description: Wooden dresser, no mod suits but mod dressers are here.
  components:
  - type: Sprite
    sprite: SS220/Objects/Storage/ModuleFurniture/dresser.rsi
    state: dresser-foundation
  - type: Damageable
    damageModifierSet: Wood
    damageContainer: StructuralInorganic
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawn:
          MaterialWoodPlank1:
            min: 3
            max: 3
      - !type:EmptyAllContainersBehaviour
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: ModuleFurniture
    tileLayoutSize: 3,3
  - type: ContainerContainer
    containers:
      module-furniture: !type:Container
  - type: InteractionOutline
  - type: Clickable
  - type: Tag
    tags:
    - Wooden
  - type: Anchorable
  - type: Rotatable
  # - type: Construction # TODO: make it
  #   graph: Dresser
  #   node: dresser

- type: entity
  id: BaseModularPart
  abstract: true
  parent: BaseStorageItem
  name: ModularDresserPart
  description: wooden drawer for dresser
  components:
  - type: ModuleFurniturePart
    size: w1h1
  - type: Item
    size: Huge
  - type: Sprite
    sprite: SS220/Objects/Storage/ModuleFurniture/dresser.rsi
    state: drawer-wood
    layers:
    - state: drawer-wood-open
      map: ["enum.ModuleFurnitureOpenVisuals.Layer"]
  - type: Storage
    grid:
    - 0,0,5,5
    maxItemSize: Huge
  - type: ContainerContainer
    containers:
      storagebase: !type:Container
        ents: []
  # - type: GenericVisualizer
  #   visuals:
  #     enum.ModuleFurnitureOpenVisuals.Opened:
  #       enum.ModuleFurnitureOpenVisuals.Layer:
  #         True: { visible: false }
  - type: Appearance
  - type: UserInterface
    interfaces:
      enum.StorageUiKey.Key:
        type: StorageBoundUserInterface
  - type: UseDelay
    delay: 0.5
  - type: Tag
    tags:
    - Wooden
  # - type: Construction # TODO: make it
  #   graph: Dresser
  #   node: dresser


