using Content.Shared.Objectives;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;

namespace Content.Client.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
public sealed partial class ObjectiveLine : Control
{
    // this kinda will be <EntityUid, EnumWhichCommandValid>
    public event Action? OnPressed;

    public ObjectiveLine()
    {
        OptionListButton.OnPressed += (_) =>
        {
            OnPressed?.Invoke();
        };

    }

    public ObjectiveLine AddObjectiveInfo(ObjectiveInfo objectiveInfo)
    {
        Name.SetMessage(objectiveInfo.Title);
        // maybe add color for fast scrolling
        Progress.SetMessage(objectiveInfo.Progress.ToString());
        return this;
    }

    public ObjectiveLine AddTargetName(string name)
    {
        TargetName.SetMessage(name);
        return this;
    }

    public ObjectiveLine AddOwnerName(string name)
    {
        OwnerName.SetMessage(name);
        return this;
    }
}
