using Content.Client.GameTicking.Managers;
using Content.Shared.SS220.Rituals.RitualFactory;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.SS220.Rituals.Ui;

[GenerateTypedNameReferences]
public sealed partial class RitualStepPanel : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private RitualStepPrototype? _shownRitualStepProto;
    public RitualStepPanel(ProtoId<RitualStepPrototype> protoId)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _shownRitualStepProto = _prototypeManager.Index<RitualStepPrototype>(protoId);

        RitualStepName.Text = _shownRitualStepProto.Name;
        PerformRitualStepDescription.SetMessage(_shownRitualStepProto.Description);

        // TODO RitualStepTexture = _shownRitualStepProto.UiIcon

    }
}
