// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Content.Shared.SS220.Rituals.RitualFactory;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.SS220.Rituals.Ui;

[GenerateTypedNameReferences]
public sealed partial class RitualPhasePanel : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    private EntityPrototype? _shownRitualStepProto;
    public RitualPhasePanel(ProtoId<EntityPrototype> protoId, bool isNextStep)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _shownRitualStepProto = _prototypeManager.Index<EntityPrototype>(protoId);

        RitualStepName.Text = _shownRitualStepProto.Name;
        PerformRitualStepDescription.SetMessage(_shownRitualStepProto.Description);
        SetButtonState(isNextStep);
        // TODO RitualStepTexture = _shownRitualStepProto.UiIcon
    }
    private void SetButtonState(bool isNextStep)
    {
        PerformRitualStepName.Disabled = !isNextStep;
        PerformRitualStepName.Text = "Исполнить";
    }
}
