// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Client.Message;
using Content.Shared.SS220.Rituals;
using Content.Shared.SS220.Rituals.RitualFactory;

namespace Content.Client.SS220.Rituals.Ui;

[GenerateTypedNameReferences]
public sealed partial class RitualSelectorMenu : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    public event Action<BaseButton.ButtonEventArgs, string>? OnRitualButtonPressed;

    private MasterRuneParams _masterParams;

    public RitualSelectorMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateValues(MasterRuneParams pars)
    {
        _masterParams = pars;
        UpdateValues();
    }

    public void UpdateValues()
    {
        Recharge.SetMarkup($"Recharge: {_masterParams.Recharge} ");
        Charge.SetMarkup($"Charge: {_masterParams.Charge} ");
        MaxCharge.SetMarkup($"MaxCharge: {_masterParams.MaxCharge} ");
        Efficency.SetMarkup($"Efficency: {_masterParams.Efficiency} ");
    }

    public void PopulateRitualButtons(List<string> ritualsProto)
    {
        RitualListContainer.Children.Clear();

        var group = new ButtonGroup();
        foreach (var proto in ritualsProto)
        {
            var ritButton = new RitualButton
            {
                Text = Loc.GetString(proto),
                Id = proto,
                Group = group,
                StyleClasses = { "OpenBoth" }
            };

            ritButton.OnButtonDown += args => OnRitualButtonPressed?.Invoke(args, ritButton.Id);
            RitualListContainer.AddChild(ritButton);
        }
    }

    public void UpdateRitualPhasePanels(ProtoId<RitualPrototype> protoId, RitualQualityEnum currentRitualQuality) //<-- заменить на внутренную переменную!
    {
        RitualStepsContainer.Children.Clear();
        var ritualProto = _prototypeManager.Index<RitualPrototype>(protoId);

        if (ritualProto.RitualSteps == null)
            return; // TODO LOG IT

        foreach (var ritualStepId in ritualProto.RitualSteps[currentRitualQuality].Values)
        {
            var newRitualStepPanels = new RitualPhasePanel(ritualStepId, true);
            RitualStepsContainer.AddChild(newRitualStepPanels);
        }
    }


    private sealed class RitualButton : Button
    {
        public string? Id;
    }
}
