name: Переименование "[Идея]" на "[F]:" в DevTeam220

on:
  workflow_dispatch:

jobs:
  rename-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Переименование задач в DevTeam220
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.URPRICE_PAT }}
          script: |
            const issues = await github.paginate(
              github.rest.issues.listForRepo,
              {
                owner: "SerbiaStrong-220",
                repo: "DevTeam220",
                state: "open",
                per_page: 100,
              }
            );
            const filtered = issues.filter(issue => issue.title.includes("[Идея]"));
            for (const issue of filtered) {
              const newTitle = issue.title.replace("[Идея]", "[F]:");
              if (newTitle !== issue.title) {
                await github.rest.issues.update({
                  owner: "SerbiaStrong-220",
                  repo: "DevTeam220",
                  issue_number: issue.number,
                  title: newTitle,
                });
                console.log(`Задача #${issue.number} переименована: ${newTitle}`);
              }
            }
